name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: apt-get install -y libsdl2-dev 
    - name: make
      run: make -j
    - name: make check
      run: echo make check
    - name: make distcheck
      run: echo make distcheck
