name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev
    - name: make clean
      run: make clean
    - name: make
      run: make -j
    - name: run_tui
      run: echo ./run_tui.sh 4
