name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Install Ubuntu packages
      run: sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev
      if: matrix.os == 'ubuntu-latest'
    - name: Install Mac packages, setup framework
      run: brew install sdl2
      if: matrix.os == 'macos-latest'
    - name: Debuggging, copy framework
      run: ls /Library/Frameworks/ && mkdir -p /Library/Frameworks/SDL2.framework && cp -r /usr/local/include/SDL2/ /Library/Frameworks/SDL2.framework/
      if: matrix.os == 'macos-latest'
    - name: make clean then make
      run: make clean && make -j
