name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Install Ubuntu packages
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev
    - name: make clean then make
    - run: make clean
    - run: make -j
