name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Install Ubuntu packages
      run: sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev
      if: matrix.os == 'ubuntu-latest'
    - name: Install Mac packages (probably too many)
      run: brew install sdl sdl_image sdl_mixer sdl_ttf portmidi && pip3 install pygame
      if: matrix.os == 'macos-latest'
    - name: make clean then make
      run: make clean && make -j
